knowledge_task:
  description: >
    Summarize the key points from the uploaded PDF.
  expected_output: >
    A concise summary of the document.
  agent: knowledge_agent

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
